[package]
name = "devptp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.103"
iroh = "1.0.1"
iroh-ping = "1.0.0"
iroh-tickets = "1.0.0"
tokio = { version = "1.52.3", features = ["full"] }
tracing-subscriber = "0.3.23"
cdevptp = { path = "../cdevptp/" }
rdevptp = { path = "../rdevptp/" }
